# Note: if you modify this file, don't forget to update
# checksum in .drone.sec with:
# drone secure --repo google/WebFundamentals --checksum
clone:
  depth: 1
cache:
  mount:
    - node_modules
build:
  image: b.gcr.io/wf-ci-images/drone:20160927
  commands:
    - npm install
    - gulp presubmit
    - gulp build
    - gcloud config set project web-central
    - gcloud app deploy -v ci-test app.yaml
